In [1]:
import pandas as pd
import pickle
import os
from experiment import *

# Creating an example for testing

Select the first 10 sensors, and only day 2012-03-01 7:00 to 22:55 from the network. Verify if the sensor's distances matches the adjacency matrix.

In [2]:
df = pd.read_hdf('data/METRLA/metr-la.h5').iloc[:, :1000]
df.head()

773869     767541     767542     717447     717446  \
2012-03-01 00:00:00  64.375000  67.625000  67.125000  61.500000  66.875000   
2012-03-01 00:05:00  62.666667  68.555556  65.444444  62.444444  64.444444   
2012-03-01 00:10:00  64.000000  63.750000  60.000000  59.000000  66.500000   
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000000   

                        717445  773062  767620     737529     717816  ...  \
2012-03-01 00:00:00  68.750000  65.125  67.125  59.625000  62.750000  ...   
2012-03-01 00:05:00  68.111111  65.000  65.000  57.444444  63.333333  ...   
2012-03-01 00:10:00  66.250000  64.500  64.250  63.875000  65.375000  ...   
2012-03-01 00:15:00   0.000000   0.000   0.000   0.000000   0.000000  ...   
2012-03-01 00:20:00   0.000000   0.000   0.000   0.000000   0.000000  ...   

                        772167  769372     774204     769806  717590  \
2012-03-01 00:00:00  45.625000  65.500  64.500000  66.428571  66.875   
2012-03-01 00:05:00  50.666667  69.875  66.666667  58.555556  62.000   
2012-03-01 00:10:00  44.125000  69.000  56.500000  59.250000  68.125   
2012-03-01 00:15:00   0.000000   0.000   0.000000   0.000000   0.000   
2012-03-01 00:20:00   0.000000   0.000   0.000000   0.000000   0.000   

                        717592     717595     772168     718141  769373  
2012-03-01 00:00:00  59.375000  69.000000  59.250000  69.000000  61.875  
2012-03-01 00:05:00  61.111111  64.444444  55.888889  68.444444  62.875  
2012-03-01 00:10:00  62.500000  65.625000  61.375000  69.857143  62.000  
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000  
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000  

[5 rows x 207 columns]

In [3]:
df.index = pd.to_datetime(df.index)
df.index.freq = None

In [4]:
try:
    # Slice the DataFrame to only include rows between 7:00 and 22:55 on 2012-03-01
    # And to only include the first 20 columns
    filtered_df = df.loc['2012-03-01 7:00':'2012-03-01 22:55', df.columns[:20]]
except Exception as e:
    print(f"An error occurred: {e}")

In [5]:
filtered_df.head()

773869     767541     767542     717447     717446  \
2012-03-01 07:00:00  68.250  65.125000  31.750000  49.750000  48.500000   
2012-03-01 07:05:00  68.125  65.125000  26.875000  51.000000  45.000000   
2012-03-01 07:10:00  69.000  64.500000  31.625000  50.625000  39.750000   
2012-03-01 07:15:00  69.000  63.555556  28.222222  48.111111  44.888889   
2012-03-01 07:20:00  68.125  64.625000  29.250000  45.125000  48.500000   

                        717445     773062     767620  737529     717816  \
2012-03-01 07:00:00  58.750000  67.000000  62.500000  55.000  13.285714   
2012-03-01 07:05:00  59.125000  64.500000  65.000000  60.375  11.000000   
2012-03-01 07:10:00  57.625000  67.750000  62.000000  62.875  11.250000   
2012-03-01 07:15:00  57.111111  66.333333  62.111111  58.125   7.111111   
2012-03-01 07:20:00  55.375000  64.375000  63.375000   0.000  11.714286   

                        765604     767471  716339  773906     765273  \
2012-03-01 07:00:00  58.125000  64.750000  17.000   66.50  10.250000   
2012-03-01 07:05:00  62.500000  63.750000  20.750   67.25   7.500000   
2012-03-01 07:10:00  62.250000  63.125000  19.375   68.25   8.750000   
2012-03-01 07:15:00  62.222222  63.333333  18.125   66.00   6.777778   
2012-03-01 07:20:00  60.375000  61.142857  16.875   64.75   9.875000   

                        716331     771667     716337     769953     769402  
2012-03-01 07:00:00  43.750000  33.000000  52.875000  59.875000  63.875000  
2012-03-01 07:05:00  44.500000  33.000000  52.875000  63.875000  63.750000  
2012-03-01 07:10:00  40.500000  32.375000  52.875000  59.375000  64.750000  
2012-03-01 07:15:00  36.888889  33.666667  51.888889  60.666667  60.666667  
2012-03-01 07:20:00  38.000000  32.875000  55.750000  59.750000  63.750000

In [29]:
file_path = 'data/METRLA/adj_mx_new.pkl'
with open(file_path, 'rb') as f:
    adj_mx = pickle.load(f, encoding='latin1')

In [30]:
adj_mx[2]

array([[1.        , 0.14388524, 0.1433578 , ..., 0.        , 0.34449434,
        0.27822873],
       [0.        , 1.        , 0.92753   , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.97311145, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.12031321,
        0.        ],
       [0.32921156, 0.        , 0.        , ..., 0.28058538, 1.        ,
        0.1591485 ],
       [0.        , 0.17780617, 0.        , ..., 0.        , 0.365523  ,
        1.        ]], dtype=float32)

In [31]:
adj_mx[0] = adj_mx[0][:20]

In [32]:
selected_sensors = {}

# Iterate over the items of the dictionary
for sensor_id, index in adj_mx[1].items():
    # Check if the index is between 1 and 10 (inclusive)
    if 1 <= index <= 20:
        # Add the sensor ID and index to the new dictionary
        selected_sensors[sensor_id] = index
        
    # Stop if you already have 10 items
    if len(selected_sensors) == 20:
        break

In [33]:
adj_mx[1] = selected_sensors

In [34]:
adj_mx[2] = adj_mx[2][:20, :20]

In [35]:
adj_mx[2][0]

array([1.        , 0.14388524, 0.1433578 , 0.        , 0.        ,
       0.        , 0.        , 0.1516956 , 0.        , 0.        ,
       0.2323694 , 0.18220767, 0.        , 0.34543255, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.41736084],
      dtype=float32)

In [36]:
directory = 'data'
file_name = 'adj_mx_ex.pkl'
file_path = os.path.join(directory, file_name)

# Ensure the directory exists
os.makedirs(directory, exist_ok=True)

# Save the adj_mx to a .pkl file
with open(file_path, 'wb') as f:
    pickle.dump(adj_mx, f)

In [37]:
filtered_df.to_hdf('data/example.h5', key='df', mode='w')

# Step by Step example

## Initialization and Preparation
1. If the pretraining stage is not enabled, the output of the encoder is by default a matrix \[latent_dimension, number_of_sensors\] with all entries equal to 0. Therefore, to make sure that the input to the downstream model keeps as the original, the encoder output matrix cannot be concatenated with the actual data input, but adding them will have no impact. Therefore, in sucha a case, the parameter is_concat_encoder_model will be set to False anyway.
2. set `data` and `scaler` as the global variables

In [20]:
if P.is_pretrain == False:
    P.is_concat_encoder_model = False
global data
global scaler

3. set backend devices. Check if the type of GPU, either mps or cuda, is available. Also, another options is to use the CPU.

In [5]:
if torch.backends.mps.is_available():
    device_gpu = torch.device('mps') 
if torch.cuda.is_available():
    device_gpu = torch.device('cuda')
device_cpu = torch.device('cpu')

4. Set the parameters to save the results. The results will be saved in the `save` folder. Each training execution will be in a different directory, named by dataname_datetime.

In [6]:
P.exe_id = P.dataname + '_' + datetime.now().strftime("%y%m%d-%H%M")
P.save_path = 'save/' + P.exe_id

5. Read the data file. In this example, the data is the example test data. There are only ten sensors in the example.

In [7]:
print('P.dataname == EXAMPLE')
P.data_path = './data/example.h5'
P.adj_path = './data/adj_mx_ex.pkl'
P.n_sensor = 20
data = pd.read_hdf(P.data_path).values

P.dataname == EXAMPLE


First two rows: the reading of 10 sensors at 10 am and 10:05

In [8]:
data[0]

array([65.   , 65.25 , 68.   , 41.25 , 41.625, 53.625, 63.625, 64.375,
       58.75 , 15.125])

In [9]:
data[1]

array([64.125, 65.375, 68.75 , 33.125, 26.125, 55.   , 65.375, 63.75 ,
       59.25 , 17.625])

6. Apply the scaler to the sensor readings. The data is scaled based on the mean and standard deviation of the data.

In [10]:
scaler = StandardScaler()
data = scaler.fit_transform(data)
print('data.shape:', data.shape)

data.shape: (60, 10)


First two rows after the scaling: the reading of 10 sensors at 10 am and 10:05.

In [11]:
data[0]

array([ 0.660179  ,  0.68204265,  0.92254278, -1.41686762, -1.38407215,
       -0.33461701,  0.53992893,  0.60551988,  0.11358779, -3.7016189 ])

In [13]:
data[1]

array([ 0.58365623,  0.69297447,  0.98813373, -2.1274362 , -2.73961836,
       -0.21436694,  0.69297447,  0.55086076,  0.15731508, -3.48298241])

## Set all the parameters

In [2]:
os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = '1'
P = type('Parameters', (object,), {})()
P.dataname = 'EXAMPLE'
P.model = 'LSTM'
P.seed = 0

P.t_train = 0.8
P.t_val = 0.1
P.s_train = 0.6
P.s_val = 0.2

P.timestep_in = 12
P.timestep_out = 12
P.n_channel = 1
P.batch_size = 64

P.lstm_hidden_dim = 128
P.gwnet_is_adp_adj = True
P.gwnet_is_SGA = False

P.adj_type = 'doubletransition'
P.is_cost = False
P.cost_kernals = [1, 2, 4, 8, 16, 32, 64, 128]
P.cost_alpha = 0.5
P.cl_temperature = 1
P.is_pretrain = True
P.is_GCN_encoder = False
P.is_GCN_after_CL = True
P.augmentation = 'temporal_shifting'
P.temporal_shifting_r = 0.8
P.encoder_to_model_ratio = 1
P.is_concat_encoder_model = True

P.learn_rate = 0.001
P.pretrain_epoch = 1
P.train_epoch = 1
P.weight_decay = 0
P.is_testunseen = True
P.train_model_datasplit = 'B'
P.train_encoder_on = 'gpu'

P.example_verbose = True

# Run the entire training process

In [3]:
%run -i 'experiment.py'

P.dataname == EXAMPLE

First row at 10 am: [68.25       65.125      31.75       49.75       48.5        58.75
 67.         62.5        55.         13.28571429 58.125      64.75
 17.         66.5        10.25       43.75       33.         52.875
 59.875      63.875     ]

Second row at 10:05: [68.125 65.125 26.875 51.    45.    59.125 64.5   65.    60.375 11.
 62.5   63.75  20.75  67.25   7.5   44.5   33.    52.875 63.875 63.75 ]
data.shape: (192, 20)

First row at 10 am after scaling: [ 0.94965521  0.75991885 -1.26646543 -0.17358402 -0.24947856  0.37285669
  0.87376067  0.60054031  0.14517306 -2.38753624  0.33490941  0.73715049
 -2.16202103  0.84340285 -2.57185156 -0.53787782 -1.19057089  0.01615234
  0.44116177  0.68402431]

Second row at 10:05 after scaling: [ 0.94206575  0.75991885 -1.56245415 -0.09768948 -0.46198328  0.39562505
  0.72197158  0.7523294   0.47151959 -2.52631483  0.60054031  0.67643486
 -1.9343374   0.88893957 -2.73881955 -0.4923411  -1.19057089  0.01615234
  0.684024

/Users/xuyou/opt/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/rnn.py:83: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "


epoch 0 time used: 0  seconds  train loss: 0.6173667311668396 validation unseen nodes loss: 0.9108996987342834 validation all nodes loss: 0.9108597040176392
MODEL TRAINING DURATION: 0:00:00.320424
trainModel Ended ...

Model Testing test_a Started ...
Model Infer Start ...
ENCODER INFER DURATION: 0:00:00.044838
Model Infer End ... 2024-04-23 19:42:54.640198
MODEL INFER DURATION: 0:00:00.031259
YS.shape, YS_pred.shape, (9, 12, 4, 1) (9, 12, 4, 1)
****************************************
LSTM, test_a, Torch MSE, 5.8895868063e-01, 0.5889586806
all pred steps, LSTM, test_a, MSE, RMSE, MAE, MAPE, 114.7630310059, 10.7127504349, 9.7002811432, 15.0472193956
1 step, LSTM, test_a, MSE, RMSE, MAE, MAPE, 54.3433303833, 7.3717927933, 6.1450543404, 9.4172388315
2 step, LSTM, test_a, MSE, RMSE, MAE, MAPE, 121.1933212280, 11.0087842941, 9.9217090607, 15.3749287128
3 step, LSTM, test_a, MSE, RMSE, MAE, MAPE, 134.4552612305, 11.5954847336, 10.6547956467, 16.5525481105
4 step, LSTM, test_a, MSE, RMSE, MA

/Users/xuyou/opt/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/rnn.py:83: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
